name: main

on: [push]

jobs:
  main:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2

      - run: bun install --frozen-lockfile

      - run: bunx tsc

      - run: bun scripts/build

      - uses: daaku/gh-action-apt-install@v4
        with:
          packages: advancecomp

      - run: bun scripts/bundle

      - name: build demos
        run: |
          mkdir dist/demo -p
          echo '<!DOCTYPE html><html><body><ul>' > dist/demo/index.html
          for FILE in $( ls demo )
          do
            bunx vite build demo/$FILE --base "./" --minify false --outDir ../../dist/demo/$FILE
            echo "<li><a href=\"$FILE/\">$FILE</a></li>" >> dist/demo/index.html
          done
          echo "</ul></body></html>" >> dist/demo/index.html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - uses: actions/deploy-pages@v4
